# Generated by Django 4.0.6 on 2022-07-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')]),
        ),
    ]
